import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'ar' | 'en';

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
  isRtl: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    home: 'Home',
    features: 'Features',
    services: 'Services',
    howItWorks: 'How it Works',
    login: 'Login',
    register: 'Register',
    dashboard: 'Dashboard',
    copyright: '© 2024 CPSTORE. ALL RIGHTS RESERVED.',
    step1Title: 'Create Account',
    step1Sub: 'Sign up and deposit funds using our secure payment methods.',
    step2Title: 'Select Package',
    step2Sub: 'Browse our high-quality video, design, and growth services.',
    step3Title: 'Wait & Grow',
    step3Sub: 'Sit back while our experts handle your project and deliver results.',
    viewPackages: 'View Packages',
    professionalServices: 'Professional Services',
    cinemaProduction: 'Cinema Production',
    cinemaProductionTitle: 'Global 4K Video Production',
    cinemaProductionDesc: 'We turn your idea into a visual reality that dazzles your customers through professional editing and cinematic direction that increases your brand power.',
    visualIdentity: 'Visual Identity',
    visualIdentityTitle: 'Visual Identity Design',
    visualIdentityDesc: 'We design an unforgettable visual footprint for you, from the logo to content posters, to ensure you appear as a professional in your field.',
    growthAutomation: 'Growth & Automation',
    growthAutomationTitle: 'Expand Pages and Increase Reach',
    growthAutomationDesc: 'Increase your follower base and interaction through our advanced systems to raise reach and provide real and targeted followers.',
    exploreDetails: 'Explore Details',
    customPrice: 'Custom',
    priceSuffix: 'EGP',
    gridTitle1: 'Video Production',
    gridDesc1: 'Advertising production and cinematic editing that catches the target customer\'s eye immediately.',
    gridTitle2: 'Social Media Identity',
    gridDesc2: 'Integrated and professional visual identity design that highlights your brand strongly.',
    gridTitle3: 'Management & Ad Campaigns',
    gridDesc3: 'Professional management of your pages and launching funded campaigns that achieve the highest sales.',
    gridTitle4: 'Scaling & Reach Increase',
    gridDesc4: 'Smart automation for scaling pages and increasing followers to ensure highest real engagement.',
    webTitle: 'Website for ',
    webTitleHighlight: 'Your Brand',
    limitedTime: 'Limited Time Offer',
    originalPriceLabel: 'Instead of 12,000 EGP',
    launchProject: 'Own Your Professional Presence',
    orderWebAction: 'Order Your Site Now',
    instantBooking: 'Available for immediate booking',
    privacyPolicy: 'Privacy Policy',
    dynamicWebTitle: '100% Dynamic Site',
    dynamicWebDesc: 'Full interaction and super fast performance',
    controlPanelTitle: 'Full Control Panel',
    controlPanelDesc: 'Edit and add content with ease',
    medicalClinics: 'Medical Clinics',
    onlineStores: 'Online Stores',
    restaurantsCafes: 'Restaurants & Cafes',
    realEstateCompany: 'Real Estate Companies',
    bentoSectionTitle: 'Why Choose ',
    bentoSectionTitleSuffix: '?',
    bentoSectionSub: 'Elevate your pages to the elite level! More views and followers through exclusive designs and global 4K videos designed with the highest cinematic creativity standards.',
    bentoTitle1: 'Creative Production with Global 4K Quality',
    bentoDesc1: 'Vibrant social media posters and integrated packaging design that reflects the weight and luxury of your project, in integration with cinematic video editing and creative script writing that catches the target customer\'s eye and doubles your sales.',
    bentoFeature1: '✦ Custom Visual Identity',
    bentoFeature2: '✦ Professional Cinematic Direction',
    bentoTitle2: 'Smart and Instant Execution',
    bentoDesc2: 'An advanced programming automation system that links your request automatically as soon as payment is confirmed to start the immediate rise of your pages.',
    bentoTitle3: 'Smart investment that doubles your sales and achieves leadership for your page',
    bentoDesc3: 'Integrated packages with discounts up to 60% (such as the 999 EGP offers) ensuring real returns and safe growth for your agency and project.',
    bentoTitle4: 'Full Technical Supervision 24/7',
    bentoDesc4: 'A specialized team monitors the performance of your campaigns and pages around the clock to ensure full stability and automatic execution, while providing a direct and immediate communication line to answer any inquiries or detail special packages.',
    talkCreativeAdvisor: 'Talk to Creative Advisor',
    sliderHeaderTag: 'The Power of Reach',
    sliderHeaderPhrase1: 'Smart Growth',
    sliderHeaderPhrase2: 'Global Quality',
    sliderHeaderPhrase3: 'Instant Result',
    campaignManagementTitle: 'Page Management & Ad Campaigns',
    campaignManagementSub: 'Achieve real growth for your page now',
    packageStandard: 'Standard',
    packageAdvanced: 'Advanced',
    packagePro: 'Professional',
    pageManagementPackage: 'Page Management Package',
    followersCount1: '10,000+ Real Followers',
    followersCount2: '25,000+ Real Followers',
    designsCount1: '10 Professional Designs',
    designsCount2: '15 Professional Designs',
    designsCount3: '20 Professional Designs',
    fundedAd4Days: '4-Day Funded Ad',
    fundedAd7Days: '7-Day Funded Ad',
    videoAds7: '7 Video Ads',
    mostRequested: 'Most Requested',
    bookNow: 'Book Now',
    bookNowWhatsApp: 'Book Now / WhatsApp',
    confirmationTitle: 'Booking Confirmation',
    confirmationSub: 'Complete the following details to be redirected to WhatsApp to complete your booking and our team will contact you.',
    selectedPackageLabel: 'Selected Package:',
    totalAmountLabel: 'Total Amount:',
    customerNameLabel: 'Your Name',
    customerNamePlaceholder: 'Enter your name here',
    pageUrlLabel: 'Your Page Link (Target)',
    pageUrlPlaceholder: 'https://www.facebook.com/...',
    confirmAndWhatsApp: 'Confirm & Go to WhatsApp',
    paymentMethodLabel: 'Current Available Payment Method',
    paymentMethodSelect: 'Choose the payment method that suits you',
    paymentMethodEtisalat: '📱 Etisalat Cash',
    paymentMethodBehance: '🎨 Behance Platform (Direct Payment)',
    etisalatInstructionsTitle: 'Etisalat Cash Payment Instructions:',
    etisalatInstructionsText: 'Transfer the amount of {price} EGP to the following Etisalat Cash wallet:',
    etisalatWalletNumber: '01153339499',
    etisalatNote: '* After successfully transferring the amount, please write the wallet number you transferred from below to confirm the booking.',
    behanceInstructionsTitle: 'Behance Platform Payment Instructions:',
    behanceInstructionsText: 'Please visit our direct account on Behance to complete the payment or contract and transfer the value of {price} EGP:',
    behanceUrl: 'behance.net/724199355',
    behanceNote: '* Please write your account name or registered email on the Behance platform in the field below to confirm and match the real request.',
    confirmationDetailsLabel: 'Transfer Details for Confirmation',
    senderDetailsPlaceholderEtisalat: 'Example: 011XXXXXXXX (Your wallet number)',
    senderDetailsPlaceholderBehance: 'Example: name@behance.net or your account name',
    videoSectionTag: 'Cinema Production',
    videoSectionTitle: 'We create a visual footprint ',
    videoSectionDesc: 'At Control P, we don\'t just make videos; we build a strong brand for you through creative scripts and professional editing that makes your brand stand alone at the top.',
    creativeScripting: 'Creative Scripting',
    fastDelivery: 'Fast Delivery',
    orderVideoAction: 'Order Video Now',
    ourWorks: 'Our Works',
    clientTrust: 'Clients Trust Us',
    // Web Dev Modal
    orderWebTitle: "Order Website",
    projectName: "Project Name",
    businessType: "Business Type",
    projectDesc: "Project Description",
    uploadAssets: "Upload Logo or Assets (Optional)",
    continuePayment: "Continue to Payment",
    stepPayment: "Payment & Confirmation",
    totalAmount: "Total Amount",
    paymentMethods: "Payment Methods",
    etisalatCash: "Etisalat Cash",
    binance: "Binance PAY",
    senderNumber: "Sender Phone Number",
    confirmOrder: "Confirm & Send Request",
    orderSuccess: "Order Sent Successfully! Our team will contact you soon.",
    selectType: "Select Business Type",
    corp: "Corporate",
    eCommerce: "E-Commerce",
    medical: "Medical",
    realEstate: "Real Estate",
    restaurant: "Restaurant/Cafe",
    promoBadge1: 'THE POWER OF REACH',
    promoTitle1Highlight: 'The Power in Reach',
    promoSub1: 'We give you control and full command over your digital presence, to lead your page towards visibility and dominate your competitors with smart and innovative marketing tools and campaigns.',
    promoBadge2: 'Limited Time Offer ⚡',
    promoTitle2: 'Bundled packages with discounts up to 60% starting from 999 EGP',
    promoSub2: 'Exceptional custom offers and packages that ensure your project and agency get the highest possible returns and leadership in the market with the best investment cost.',
    promoAction1: 'View 999 EGP Packages',
    promoAction2: 'Contact Us Directly'
  },
  ar: {
    home: 'الرئيسية',
    features: 'المميزات',
    services: 'الخدمات',
    howItWorks: 'كيف يعمل',
    login: 'تسجيل دخول',
    register: 'تسجيل',
    dashboard: 'لوحة التحكم',
    copyright: '© 2024 CPSTORE. جميع الحقوق محفوظة.',
    step1Title: 'إنشاء حساب',
    step1Sub: 'قم بالتسجيل وشحن رصيدك باستخدام طرق الدفع الآمنة الخاصة بنا.',
    step2Title: 'اختر الباقة',
    step2Sub: 'تصفح خدماتنا عالية الجودة في الفيديو والتصميم وتنمية الصفحات.',
    step3Title: 'انتظر وانمو',
    step3Sub: 'استرخِ بينما يتولى خبراؤنا معالجة مشروعك وتقديم النتائج.',
    viewPackages: 'عرض الباقات',
    professionalServices: 'خدمات احترافية',
    cinemaProduction: 'إنتاج سينمائي',
    cinemaProductionTitle: 'صناعة فيديوهات 4K عالمية',
    cinemaProductionDesc: 'نحول فكرتك إلى واقع بصري يبهر عملاءك عبر مونتاج احترافي وإخراج سينمائي يزيد من قوة براندك.',
    visualIdentity: 'هوية بصرية',
    visualIdentityTitle: 'تصميم الهوية البصرية',
    visualIdentityDesc: 'نصمم لك بصمة بصرية لا تُنسى، من اللوجو وحتى بوسترات المحتوى، لضمان ظهورك كاحترافي في مجالك.',
    growthAutomation: 'نمو وأتمتة',
    growthAutomationTitle: 'تكبير الصفحات ورفع الريتش',
    growthAutomationDesc: 'زد من قاعدة متابعيك وتفاعلهم عبر أنظمتنا المتطورة لرفع الريتش وتزويد المتابعين الحقيقيين والمستهدفين.',
    exploreDetails: 'استكشف التفاصيل',
    customPrice: 'حسب الطلب',
    priceSuffix: 'ج.م',
    gridTitle1: 'صناعة الفيديوهات',
    gridDesc1: 'إنتاج إعلاني ومونتاج سينمائي يخطف عين العميل المستهدف فوراً.',
    gridTitle2: 'هوية سوشيال ميديا',
    gridDesc2: 'تصميم هوية بصرية متكاملة واحترافية تبرز علامتك التجارية بقوة.',
    gridTitle3: 'إدارة وحملات إعلانية',
    gridDesc3: 'إدارة صفحاتك باحترافية وإطلاق حملات ممولة تحقق أعلى مبيعات.',
    gridTitle4: 'تكبير ورفع الريتش',
    gridDesc4: 'أتمتة ذكية لتكبير الصفحات وتزويد المتابعين لضمان أعلى تفاعل حقيقي.',
    webTitle: 'موقع إلكتروني ',
    webTitleHighlight: 'لعلامتك التجارية',
    limitedTime: 'عرض لفترة محدودة',
    originalPriceLabel: 'بدلاً من 12,000 ج.م',
    launchProject: 'امتلك موقعك الاحترافي بأحدث التقنيات العالمية',
    orderWebAction: 'اطلب موقعك الآن',
    instantBooking: 'متاح للحجز الفوري',
    privacyPolicy: 'سياسة الخصوصية',
    dynamicWebTitle: 'موقع ديناميكي 100%',
    dynamicWebDesc: 'تفاعل كامل وسرعة فائقة في الأداء',
    controlPanelTitle: 'لوحة تحكم كاملة',
    controlPanelDesc: 'تعديل وإضافة محتوى بكل سهولة',
    medicalClinics: 'عيادات طبية',
    onlineStores: 'متاجر إلكترونية',
    restaurantsCafes: 'مطاعم وكافيهات',
    realEstateCompany: 'شركات عقارية',
    bentoSectionTitle: 'لماذا تختار ',
    bentoSectionTitleSuffix: '؟',
    bentoSectionSub: 'ارتقِ بصفحاتك إلى مستوى النخبة! مشاهدات ومتابعين أكثر عبر تصميمات حصرية وفيديوهات 4K عالمية مصممة بأعلى معايير الإبداع السينمائي.',
    bentoTitle1: 'إنتاج إبداعي بجودة 4K عالمية',
    bentoDesc1: 'بوسترات سوشيال ميديا نابضة بالحياة وتصميم عبوات متكامل يعكس ثقل وفخامة مشروعك، بالتكامل مع مونتاج فيديوهات سينمائية وصناعة سكريبت مبتكر يخطف عين العميل المستهدف ويضاعف مبيعاتك.',
    bentoFeature1: '✦ هوية بصرية مخصصة',
    bentoFeature2: '✦ إخراج سينمائي احترافي',
    bentoTitle2: 'تنفيذ ذكي وفوري',
    bentoDesc2: 'نظام أتمتة متطور يربط طلبك آلياً بمجرد تأكيد الدفع لبدء الصعود الفوري لصفحاتك.',
    bentoTitle3: 'استثمار ذكي يضاعف مبيعاتك ويحقق لصفحتك الريادة',
    bentoDesc3: 'باقات مدمجة بخصومات تصل إلى 60% (مثل عروض الـ 999 ج.م) تضمن لوكالتك ومشروعك عوائد حقيقية ونمو آمن.',
    bentoTitle4: 'إشراف فني وإدارة كاملة 24/7',
    bentoDesc4: 'فريق متخصص يراقب أداء حملاتك وصفحاتك على مدار الساعة لضمان الثبات الكامل والتنفيذ التلقائي، مع توفير خط تواصل مباشر وفوري للإجابة على أي استفسارات أو تفصيل باقات خاصة.',
    talkCreativeAdvisor: 'تحدث مع المستشار الإبداعي',
    sliderHeaderTag: 'قوة الوصول',
    sliderHeaderPhrase1: 'نمو ذكي',
    sliderHeaderPhrase2: 'جودة عالمية',
    sliderHeaderPhrase3: 'نتيجة فورية',
    campaignManagementTitle: 'إدارة الصفحات والحملات الإعلانية',
    campaignManagementSub: 'حقق نمو حقيقي لصفحتك الآن',
    packageStandard: 'قياسي',
    packageAdvanced: 'متقدم',
    packagePro: 'احترافي',
    pageManagementPackage: 'باكدج إدارة الصفحات',
    followersCount1: '10000+ متابع حقيقيين',
    followersCount2: '25000+ متابع حقيقيين',
    designsCount1: '10 تصاميم احترافية',
    designsCount2: '15 تصميم احترافي',
    designsCount3: '20 تصميم احترافي',
    fundedAd4Days: 'إعلان ممول 4 أيام',
    fundedAd7Days: 'إعلان ممول لمدة 7 أيام',
    videoAds7: '7 فيديوهات إعلانية',
    mostRequested: 'الأكثر طلباً',
    bookNow: 'احجز الآن',
    bookNowWhatsApp: 'احجز الآن / تواصل واتساب',
    confirmationTitle: 'تأكيد الحجز',
    confirmationSub: 'أكمل البيانات التالية لتحويلك إلى واتساب لإتمام الحجز وسيقوم الفريق بالتواصل معك.',
    selectedPackageLabel: 'الباقة المختارة:',
    totalAmountLabel: 'الإجمالي:',
    customerNameLabel: 'الاسم الكريم',
    customerNamePlaceholder: 'اكتب اسمك هنا',
    pageUrlLabel: 'رابط صفحتك (المستهدفة)',
    confirmAndWhatsApp: 'تأكيد والانتقال للواتساب',
    paymentMethodLabel: 'طريقة التحويل والدفع المتاحة حالياً',
    paymentMethodSelect: 'اختر وسيلة الدفع المناسبة لك',
    paymentMethodEtisalat: '📱 اتصالات كاش (Etisalat Cash)',
    paymentMethodBehance: '🎨 منصة بيهانس الدفع المباشر (Behance Platform)',
    etisalatInstructionsTitle: 'تعليمات الدفع عبر اتصالات كاش (Etisalat Cash):',
    etisalatInstructionsText: 'قم بتحويل المبلغ وهو {price} جنيه إلى محفظة اتصالات كاش على الرقم التالي:',
    etisalatWalletNumber: '01153339499',
    etisalatNote: '* بعد إتمام عملية تحويل المبلغ بنجاح، يرجى كتابة رقم المحفظة التي قمت بالتحويل منها بالأسفل لتأكيد الحجز.',
    behanceInstructionsTitle: 'تعليمات الدفع عبر منصة بيهانس (Behance Hire):',
    behanceInstructionsText: 'برجاء زيارة حسابنا المباشر على بيهانس لإتمام الدفع أو التعاقد والتحويل بقيمة {price} جنيه:',
    behanceUrl: 'behance.net/724199355',
    behanceNote: '* يرجى كتابة اسم حسابك أو بريدك الإلكتروني المسجل على منصة بيهانس في الحقل بالأسفل للتأكيد ومطابقة الطلب الحقيقي.',
    confirmationDetailsLabel: 'بيانات التحويل للتأكيد',
    senderDetailsPlaceholderEtisalat: 'مثال: 011XXXXXXXX (رقم محفظتك)',
    senderDetailsPlaceholderBehance: 'مثال: name@behance.net أو اسم حسابك',
    videoSectionTag: 'إنتاج سينمائي',
    videoSectionTitle: 'نصنع لك بصمة بصرية ',
    videoSectionDesc: 'في Control P، لا نصنع فيديوهات فحسب، بل نبني لك برانداً قوياً عبر سكريبتات إبداعية ومونتاج احترافي يجعل علامتك التجارية تقف وحدها في القمة.',
    creativeScripting: 'سكريبتات إبداعية',
    fastDelivery: 'سرعة في التنفيذ',
    orderVideoAction: 'اطلب الفيديو الآن',
    ourWorks: 'أعمالنا',
    clientTrust: 'عميل يثق بنا',
    // Web Dev Modal
    orderWebTitle: "طلب موقع إلكتروني",
    projectName: "اسم المشروع",
    businessType: "نوع النشاط",
    projectDesc: "وصف المشروع",
    uploadAssets: "ارفع اللوجو أو الملفات (اختياري)",
    continuePayment: "المتابعة للدفع",
    stepPayment: "الدفع والتأكيد",
    totalAmount: "المبلغ الإجمالي",
    paymentMethods: "طرق الدفع المتاحة",
    etisalatCash: "اتصالات كاش (011xxxxxxx)",
    binance: "بينانس باي",
    senderNumber: "رقم الهاتف المحول منه",
    confirmOrder: "تأكيد الدفع وإرسال الطلب",
    orderSuccess: "تم إرسال طلبك بنجاح! سيتواصل معك فريقنا قريباً.",
    selectType: "اختر نوع النشاط",
    corp: "شركة / مؤسسة",
    eCommerce: "متجر إلكتروني",
    medical: "عيادة / مركز طبي",
    realEstate: "عقارات",
    restaurant: "مطعم / كافيه",
    promoBadge1: 'THE POWER OF REACH',
    promoTitle1Highlight: 'القوة في الوصول',
    promoSub1: 'نمنحك السيطرة والتحكم الكامل في حضورك الرقمي، لتقود صفحتك نحو الانتشار وتكتسح منافسيك بأدوات وحملات تسويقية ذكية ومبتكرة.',
    promoBadge2: 'عرض لفترة محدودة ⚡',
    promoTitle2: 'باقات مدمجة بخصومات تصل إلى 60% تبدأ من 999 ج.م',
    promoSub2: 'عروض وباقات استثنائية مخصصة تضمن لمشروعك ووكالتك أعلى العوائد الممكنة والريادة في السوق وبأفضل تكلفة استثمارية.',
    promoAction1: 'استعرض باقات الـ 999 ج.م',
    promoAction2: 'اتصل بنا مباشرة'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLang] = useState<Language>(() => {
    const saved = localStorage.getItem('lang');
    return (saved as Language) || 'ar';
  });

  useEffect(() => {
    localStorage.setItem('lang', lang);
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  }, [lang]);

  const t = (key: string) => {
    return translations[lang][key] || key;
  };

  const isRtl = lang === 'ar';

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, isRtl }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
};
